# Allows shopware/shopware to read collaborators

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/shopware(-private)?:.*
claim_pattern:
  workflow_ref: shopware/shopware(-private)?/.github/workflows/.*

permissions:
  metadata: read
  members: read

repositories:
  - shopware
  - shopware-private
