issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/SwagCommercial:.*
claim_pattern:
  workflow_ref: shopware/SwagCommercial/.github/workflows/backport.ya?ml@refs/heads/trunk

permissions:
  contents: write
  pull_requests: write

repositories:
  - SwagCommercial
